<div class="page-header">
    <h1>Crear Feria</h1>
</div>
<div class="row-fluid">

    <div class="span12" >
        <div id="res-form-ajax"><?php View::content(); ?></div>
        <?php echo Ajax::form('res-form-ajax', NULL, 'form-horizontal'); ?>
        
        <?php echo Form::hidden('apReglamento.pkReglamento'); ?>
        <div class="control-group">
            <label class="control-label" for="apReglamento">Posicion </label>
            <div class="controls">
                <?php echo Form::text('apReglamento.posicion'); ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="apReglamento">Descripcion : </label>
            <div class="controls">
                <?php echo Form::textarea('apReglamento.descripcion', 'class="span4"') ?>
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label" for="apReglamento">Feria : </label>
            <div class="controls">
             <?php echo Form::dbSelect('apReglamento.ferias_pkFeria', 'nombre', array('ap_ferias', 'find', 'pkFeria'), 'Ninguno') ?>
            </div>
        </div>


        <div class="form-actions">
            <?php echo Form::submit('Guardar Datos', 'class="btn btn-small  btn-primary"'); ?>
            <?php echo Html::linkAction('', 'Cancelar', 'class="btn btn-small"'); ?>


        </div>
        <?php echo Form::close() ?>
    </div>
</div>