<!DOCTYPE html>
<html lang="es">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <title>KumbiaPHP web &amp; App Framework</title>
  <?php Tag::css('bootstrap.min') ?>
  <?php Tag::css('bootstrap-responsive') ?>
  <?php echo Html::includeCss() ?>
</head>
<body>
    <div id='content'>
        <div id='head'>
            <div class='alignright'>
                <p id='config'>
                    <span class='app'><?php echo basename(dirname(APP_PATH)) ?></span>
                    <?php echo Html::link('pages/show/kumbia/status/', 'Config', 'title="Ver configuración de la aplicación"') ?>
                </p>
             </div>
             
            <h1 id='logo'>KumbiaPHP</h1>
            <h2 id='info-app'>web &amp; app Framework versión <?php echo kumbia_version() ?></h2>
        </div>

        <?php View::content(); ?>

        <?php View::partial('kumbia/footer') ?>
    </div>
</body>
</html>
