<div class="navbar navbar-inverse">
    <div class="navbar-inner">
        <div class="container-fluid">

            <div class="row-fluid">

                <div class="span3" style="height: 70px;">
                    <div class="pull-left">
                        <?php echo Html::img('logo_conciytey.png', 'Conciytey', ' class="pull-left"'); ?>     




                    </div>
                </div>
                <div class="span6" style="text-align: center;">

                    <?php $feria = Load::model('ap_ferias')->find_first('activo=1'); ?>
                    <h2 style="margin: 0px; line-height: 40px;" class="white"><?php echo 'Sistema de Transporte'; ?> </h2>
                    <span style="color: #fff; font-size: 25px;" class="label label-inverse  label-large arrowed-in arrowed-in-right"><span class="infobox-text"><?php echo $feria->nombre; ?></span></span>


                </div>

                <div class="span3">
                    <ul class="nav ace-nav pull-right">


                        <li class="light-blue user-profile" style=" min-height: 70px;max-height: 70px;">
                            <div class="media">
                                <a class="pull-left" href="#">
                                    <?php echo Html::img('upload/' . Auth::get('login') . '.png', NULL, ' class="nav-user-photo" style="margin-top:7px;"'); ?>  
                                </a>
                                <div class="media-body">
                                    <a class="user-menu dropdown-toggle" href="#" data-toggle="dropdown" id="lin_user">                                       
                                        <span id="user_wrap">
                                            <span style="display: inline-block; width: 100%"> <small>Bienvenido,</small></span>
                                            <span style="display: inline-block; width: 80%; white-space: nowrap; text-overflow: ellipsis; display: inline-block;overflow: hidden;  text-overflow: ellipsis; vertical-align: top; white-space: nowrap;">        <?php echo (Auth::get('nombres')) ?></span>
                                            <span style="display: inline-block; width: 90%"> <small>Usuario:</small>
                                                <?php echo(Auth::get('login')) ?></span>
                                        </span>

                                        <span style="color: #fff;"> <i class="icon-caret-down "></i></span>
                                    </a>
                                    <ul id="user_menu" class="pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-closer">
                                        <li><?php echo Html::link('admin/usuarios/perfil', '<i class="icon-user"></i>Perfil') ?></li>
                                        <li class="divider"></li>
                                        <li><?php echo Html::link('admin/index/logout', '<i class="icon-off"></i>Salir') ?></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>