<div class="page-header">
    <h1>Usuarios del Sistema</h1>
</div>
<div id="mensajes_flash" >        
    <?php View::content() ?>
</div> 
<?php
    View::partial('aplicacion/backend_header_action', FALSE, array('texto' => 'Crear Usuario', 'opciones' => FALSE));
    $dt = new DataTable($usuarios);
    $dt->addHeaders('id', 'Login', 'Nombres', 'Correo Electronico', 'Estado', 'Editar');
    $dt->addFields('id', 'login', 'nombres', 'email');
    $dt->imgLink('icon-eye-open|icon-eye-close',
            'admin/usuarios/activar|admin/usuarios/desactivar', '', 'activo');
    $dt->imgLink('icon-edit', 'admin/usuarios/editar');
    echo $dt->render('class="table table-bordered table-striped"');
?>